Repository Just-12-More/PicPle-FE, pull requests merged in 2025-05, with the labels that each got.

#4 Feature/#3 router
  lib/main.dart
  lib/presentation/home/view/home_page.dart
  lib/presentation/splash/controller/splash_contract.dart
  lib/presentation/splash/controller/splash_controller.dart
  lib/presentation/splash/view/splash_page.dart
  lib/routes.dart
Labels: ✨ FEAT

#7 ⚙️ Setting - gitignore 업데이트
  .gitignore
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  ios/Runner.xcworkspace/contents.xcworkspacedata
  ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
Labels: ❤️‍🩹 CHORE

#9 Feature/#8 디자인 시스템 정의
  assets/fonts/Pretendard-Bold.ttf
  assets/fonts/Pretendard-Regular.ttf
  assets/fonts/Pretendard-SemiBold.ttf
  lib/presentation/theme/picple_colors.dart
  lib/presentation/theme/picple_typography.dart
  pubspec.yaml
Labels: 🎨 DESIGN, ✨ FEAT

#10 ✨ Feature - 홈 화면 UI 구현
  .gitignore
  android/app/build.gradle
  android/app/src/main/kotlin/com/just/twelve/more/picple/picple/MainActivity.kt
  assets/icons/ic_home.svg
  assets/icons/ic_location.svg
  assets/icons/ic_profile.svg
  assets/icons/ic_refresh.svg
  assets/icons/ic_upload.svg
  ios/Runner.xcodeproj/project.pbxproj
  lib/config.dart
  lib/main.dart
  lib/presentation/component/picple_bottom_navigation_bar.dart
  lib/presentation/home/view/home_page.dart
  lib/routes.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨ FEAT, 📱 UI

#12 Feature/#11 kakao sns login
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  lib/config.dart
  lib/constants.dart
  lib/data/dio_client.dart
  lib/data/locator.dart
  lib/main.dart
  lib/models/auth/login_request.dart
  lib/models/auth/login_response.dart
  lib/presentation/login/controller/login_controller.dart
  lib/presentation/login/view/login_page.dart
  lib/services/auth_service.dart
  lib/services/storage_service.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨ FEAT

#13 Feature/#11 kakao sns login
  assets/icons/ic_kakao.svg
  assets/icons/ic_picple.png
  lib/presentation/login/controller/login_controller.dart
  lib/presentation/login/view/login_page.dart
Labels: ✨ FEAT

#15 ✨ Feature - 네이버맵 OverlayImage Preload & Resize 로직
  assets/images/img_placeholder.png
  lib/core/util/image_utils.dart
  lib/core/util/naver_map_utils.dart
  lib/presentation/home/view/home_page.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨ FEAT

#17 Feat: 프로필 페이지 view 추가
  lib/presentation/profile/view/profile_page.dart
  lib/routes.dart
Labels: ✨ FEAT

#21 🔨 Refactor - Riverpod스럽게 리팩토링하기
  lib/core/base/base_controller.dart
  lib/data/datasource/auth_data_source.dart
  lib/data/datasource/mock_auth_data_source.dart
  lib/data/locator.dart
  lib/data/model/request/login_request.dart
  lib/data/model/response/login_response.dart
  lib/data/repository/auth_repository.dart
  lib/data/service_providers.dart
  lib/data/services/auth_service.dart
  lib/data/services/storage_service.dart
  lib/main.dart
  lib/presentation/login/controller/login_controller.dart
  lib/presentation/login/provider/login_contract.dart
  lib/presentation/login/provider/login_notifier.dart
  lib/presentation/login/view/login_page.dart
  lib/presentation/splash/controller/splash_contract.dart
  lib/presentation/splash/controller/splash_controller.dart
  lib/presentation/splash/controller/splash_notifier.dart
  lib/presentation/splash/view/splash_page.dart
  lib/routes.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨ FEAT, ♻️ REFACTOR

#23 ✨ Feature - 사진 목록 페이지 UI
  lib/core/util/date_time_utils.dart
  lib/data/api/auth_api.dart
  lib/data/api/photo_api.dart
  lib/data/api/storage_api.dart
  lib/data/datasource/auth_data_source.dart
  lib/data/datasource/fake_auth_data_source.dart
  lib/data/datasource/fake_photo_data_source.dart
  lib/data/datasource/mock_auth_data_source.dart
  lib/data/datasource/photo_data_source.dart
  lib/data/model/request/nearby_photos_request.dart
  lib/data/model/response/base_response.dart
  lib/data/model/response/login_response.dart
  lib/data/model/response/nearby_photos_response.dart
  lib/data/repository/auth_repository.dart
  lib/data/repository/photo_repository.dart
  lib/data/service_providers.dart
  lib/presentation/shared/provider/photo_list_contract.dart
  lib/presentation/shared/provider/photo_list_provider.dart
  lib/presentation/shared/view/photo_list_page.dart
  lib/presentation/splash/controller/splash_notifier.dart
  lib/presentation/splash/provider/splash_contract.dart
  lib/presentation/splash/provider/splash_notifier.dart
  lib/presentation/splash/view/splash_page.dart
  lib/routes.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨ FEAT

#24 Feature: Setting 페이지 UI
  lib/presentation/profile/view/profile_page.dart
  lib/presentation/setting/setting_page.dart
  lib/routes.dart
Labels: ✨ FEAT

#28 ✨ Feature - 게시물 업로드 #25
  android/app/src/main/AndroidManifest.xml
  ios/Podfile
  ios/Runner/Info.plist
  lib/core/util/permission_utils.dart
  lib/data/api/photo_api.dart
  lib/data/datasource/fake_photo_data_source.dart
  lib/data/datasource/photo_data_source.dart
  lib/data/model/request/upload_photo_request.dart
  lib/data/repository/photo_repository.dart
  lib/presentation/component/picple_bottom_navigation_bar.dart
  lib/presentation/upload/provider/upload_contract.dart
  lib/presentation/upload/provider/upload_provider.dart
  lib/presentation/upload/view/upload_page.dart
  lib/routes.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨ FEAT
